### ISSUE TITLE
Design a simple webapp that uses the API

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/evolutions#1]
Design a simple webapp that uses the `evolutions` API to display pokemon evolution chain.

**Comment by tconroy** [comment]
Hey @anshumanv! 👋 This seems like a fun one. Do you want the webapp to be externally hosted or in a `demo` dir of this repo?

**Comment by anshumanv** [comment]
Hey @tconroy  ! :wave:  
Thanks for sparing a contribution here ! :smile: 
What are your preferences on this ? I'll create a separate repo for this if you want or you can use a `demo` dir, whichever way you do is fine :+1:

**Comment by deadbirdi** [comment]
Oh this sounds neat! I'll collab with you if you want @anshumanv

**Comment by anshumanv** [comment]
Hey @sneakycr0w , thanks so much for helping in this !
@tconroy what are your views if i create a separate repo and add you guys as collab ?

**Comment by collinsnji** [comment]
Hi @anshumanv @tconroy & @sneakycr0w can I help out as well?

**Comment by anshumanv** [comment]
Sure thing @collinsnji :+1:

**Comment by deadbirdi** [comment]
I think at this point we should utilize the Projects of Github to separate each task, so none of us work on the same thing. 

Maybe an `Open`, `Assigned`, and `Completed` column(s)? You wanna get that started @anshumanv?

**Comment by anshumanv** [comment]
Good idea @sneakycr0w , lemme add you guys here for the time being.

**Comment by deadbirdi** [comment]
I think it'd be a good idea to create a separate branch too, specifically for the demo. That way you can have a Github pages hosted demo on this repo!

**Comment by anshumanv** [comment]
@tconroy @sneakycr0w @collinsnji added you guys as colab, check invite.
Let's get this done ! :smile:

**Comment by anshumanv** [comment]
I'm confused if it will we good to add the webapp here or should we have a separate repo for the task ?

**Comment by deadbirdi** [comment]
I don’t think a decision has been made. I don’t think a forked Repo is necessary, just a separate branch for the demo 

Zachary E Sohovich
Full Stack Web Developer
https://sneakycr0w.com
zach@sneakycr0w.com

**Comment by tconroy** [comment]
Hi everyone! Glad to see we have a couple interested developers :)

I would say we should just do it in this repo, in a `demo` directory. That way users have it with them when they clone the package. We could also have it on a branch so we can host via github pages.

I was thinking a little "Who's that Pokemon?" type guessing game to show off the API. 

Personally I'm a fan of React and was thinking of using Facebook's [create-react-app](https://github.com/facebookincubator/create-react-app) for this, but if you guys would rather not use react Im OK with that, too!

**Comment by anshumanv** [comment]
Okay @sneakycr0w let's got with a separate branch policy then, make one infact !

> I was thinking a little "Who's that Pokemon?" type guessing game to show off the API.

@tconroy looks interesting, let's go with that.
The webapp will mostly be single paged so React would fit in well here, views on this @sneakycr0w  @collinsnji

**Comment by deadbirdi** [comment]
I’m most familiar with React as well. 

Zachary E Sohovich
Full Stack Web Developer
https://sneakycr0w.com
zach@sneakycr0w.com

**Comment by anshumanv** [comment]
It's settled then, @sneakycr0w start up a branch and let's get started.

**Comment by PawanWagh** [comment]
@anshumanv I am also interested.

**Comment by deadbirdi** [comment]
So it looks like I made a mistake @anshumanv. I thought that github allowed Github pages via any branch, but it doesn't. I still think branching is the smart idea, but we'll put the demo site in a demo folder on the `master` branch.

**Edit for Clarity**: I'm going to create a branch called `demo` that we will merge into the `master` branch when the demo is ready. It'll store the demo in a folder in the root called `demo`.

**Comment by anshumanv** [comment]
@sneakycr0w thanks for checking that out.
My thoughts on this are to keep this repo clean and let it just serve the API part.
So just made a new repo here https://github.com/anshumanv/evolutions-webapp and added you guys as collab, let's follow up there.
@tconroy @collinsnji

**Comment by anshumanv** [comment]
https://github.com/anshumanv/evolutions-webapp/issues/1

**Comment by anshumanv** [comment]
Closing this as we are continuing in https://github.com/anshumanv/evolutions-webapp
